spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:tasks;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

app:
  jwt:
    secret-key: 242eb4a8a4a6f7c05bcf13ee4ce883dc294785f7cce98b5329843f9fd9238926
    expiration-ms: 60000