spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:tasks;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

app:
  jwt:
    secret-key: 404c087a26f258c11fc710cec0176b30
    expiration-ms: 60000